// Generated by gencpp from file beginner_tutorials/dis.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_DIS_H
#define BEGINNER_TUTORIALS_MESSAGE_DIS_H

#include <ros/service_traits.h>


#include <beginner_tutorials/disRequest.h>
#include <beginner_tutorials/disResponse.h>


namespace beginner_tutorials
{

struct dis
{

typedef disRequest Request;
typedef disResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct dis
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::dis > {
  static const char* value()
  {
    return "0ceadde973f9e22e63aec3f9a9e20a83";
  }

  static const char* value(const ::beginner_tutorials::dis&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::dis > {
  static const char* value()
  {
    return "beginner_tutorials/dis";
  }

  static const char* value(const ::beginner_tutorials::dis&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::disRequest> should match
// service_traits::MD5Sum< ::beginner_tutorials::dis >
template<>
struct MD5Sum< ::beginner_tutorials::disRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::dis >::value();
  }
  static const char* value(const ::beginner_tutorials::disRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::disRequest> should match
// service_traits::DataType< ::beginner_tutorials::dis >
template<>
struct DataType< ::beginner_tutorials::disRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::dis >::value();
  }
  static const char* value(const ::beginner_tutorials::disRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::disResponse> should match
// service_traits::MD5Sum< ::beginner_tutorials::dis >
template<>
struct MD5Sum< ::beginner_tutorials::disResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::dis >::value();
  }
  static const char* value(const ::beginner_tutorials::disResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::disResponse> should match
// service_traits::DataType< ::beginner_tutorials::dis >
template<>
struct DataType< ::beginner_tutorials::disResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::dis >::value();
  }
  static const char* value(const ::beginner_tutorials::disResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_DIS_H
