// Generated by gencpp from file beginner_tutorials/disResponse.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_DISRESPONSE_H
#define BEGINNER_TUTORIALS_MESSAGE_DISRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct disResponse_
{
  typedef disResponse_<ContainerAllocator> Type;

  disResponse_()
    : dis(0.0)  {
    }
  disResponse_(const ContainerAllocator& _alloc)
    : dis(0.0)  {
  (void)_alloc;
    }



   typedef double _dis_type;
  _dis_type dis;





  typedef boost::shared_ptr< ::beginner_tutorials::disResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::disResponse_<ContainerAllocator> const> ConstPtr;

}; // struct disResponse_

typedef ::beginner_tutorials::disResponse_<std::allocator<void> > disResponse;

typedef boost::shared_ptr< ::beginner_tutorials::disResponse > disResponsePtr;
typedef boost::shared_ptr< ::beginner_tutorials::disResponse const> disResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::disResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::disResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::disResponse_<ContainerAllocator1> & lhs, const ::beginner_tutorials::disResponse_<ContainerAllocator2> & rhs)
{
  return lhs.dis == rhs.dis;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::disResponse_<ContainerAllocator1> & lhs, const ::beginner_tutorials::disResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::disResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::disResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::disResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::disResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::disResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::disResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::disResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b1d4def45a26147d31858ffaaa8372ea";
  }

  static const char* value(const ::beginner_tutorials::disResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb1d4def45a26147dULL;
  static const uint64_t static_value2 = 0x31858ffaaa8372eaULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::disResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/disResponse";
  }

  static const char* value(const ::beginner_tutorials::disResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::disResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 dis\n"
"\n"
;
  }

  static const char* value(const ::beginner_tutorials::disResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::disResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dis);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct disResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::disResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::disResponse_<ContainerAllocator>& v)
  {
    s << indent << "dis: ";
    Printer<double>::stream(s, indent + "  ", v.dis);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_DISRESPONSE_H
